### ISSUE TITLE
FbAdsSample question

### ISSUE THREAD

**Issue by yolosaucisson** [7kfpun/AdsSampleReactNative#1]
Hi,

I saw your FbAdsSample and it helps me a little bit.
But with my app, when i install react-native-fbads, it doesn't work and only the iOS module is linking. Do I need to add compile'...:facebook:4+' to make it working?

Sincerely,

**Comment by 7kfpun** [comment]
For Android, I linked it manually.

**Comment by yolosaucisson** [comment]
Alright, i told them that there is a problem. Thanks :)
